Version 4
SymbolType CELL
RECTANGLE Normal -80 -72 96 72
WINDOW 0 8 -72 Bottom 2
WINDOW 3 8 72 Top 2
WINDOW -1 0 0 Left 0
SYMATTR Prefix X
SYMATTR Value TLC555
SYMATTR ModelFile /Users/semi/Documents/FreeCadModels/Moving_Fields/RMF_Driver/GuennyratorV2/FrequencyGenerator/TLC555.LIB
SYMATTR Description TLC555 LinCMOSTMTimer
PIN 96 16 RIGHT 8
PINATTR PinName THRES
PINATTR SpiceOrder 1
PIN 96 48 RIGHT 8
PINATTR PinName CONT
PINATTR SpiceOrder 2
PIN -80 -16 LEFT 8
PINATTR PinName TRIG
PINATTR SpiceOrder 3
PIN -80 48 LEFT 8
PINATTR PinName RESET
PINATTR SpiceOrder 4
PIN -80 16 LEFT 8
PINATTR PinName OUT
PINATTR SpiceOrder 5
PIN 96 -16 RIGHT 8
PINATTR PinName DISC
PINATTR SpiceOrder 6
PIN 96 -48 RIGHT 8
PINATTR PinName VCC
PINATTR SpiceOrder 7
PIN -80 -48 LEFT 8
PINATTR PinName GND
PINATTR SpiceOrder 8
